// <auto-generated />
namespace FH_Kiel_Ticketing_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AfterFuckedup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AfterFuckedup));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131928329_After Fucked up"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
