// <auto-generated />
namespace FH_Kiel_Ticketing_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addednamefortemplate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednamefortemplate));
        
        string IMigrationMetadata.Id
        {
            get { return "201803082011473_added name for template"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
